 [custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🎗️ Overseas,https://raw.githubusercontent.com/GIPtS/markray/main/tailormadeProxyTW.list
ruleset=📹 Emby_gf,https://raw.githubusercontent.com/GIPtS/markray/main/Emby_gf.list
ruleset=📹 Emby,https://raw.githubusercontent.com/GIPtS/markray/main/Emby_direct.list
ruleset=📹 Emby,https://raw.githubusercontent.com/GIPtS/markray/main/Emby.list
ruleset=🍎 Apple AI,https://raw.githubusercontent.com/GIPtS/markray/main/overseas.list
ruleset=🗽 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🗽 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Claude.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🎗️ Overseas`select`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇹🇼 KY TW`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇸🇬 KY SG`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇭🇰 KY HK`[]🇺🇲 GF US`[]🇺🇲 SH US`[]🇺🇲 KY US`[]自动选择`[]手动切换`[]DIRECT
custom_proxy_group=📹 Emby_gf`select`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇭🇰 KY HK`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇸🇬 KY SG`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇹🇼 KY TW`[]🇺🇲 GF US`[]🇺🇲 SH US`[]🇺🇲 KY US`[]自动选择`[]手动切换`[]DIRECT
custom_proxy_group=📹 Emby`select`[]DIRECT`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇭🇰 KY HK`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇸🇬 KY SG`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇹🇼 KY TW`[]🇺🇲 GF US`[]🇺🇲 SH US`[]🇺🇲 KY US`[]自动选择`[]手动切换
custom_proxy_group=🍎 Apple AI`select`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇸🇬 KY SG`[]🇺🇲 GF US`[]🇺🇲 SH US`[]🇺🇲 KY US`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇹🇼 KY TW`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇭🇰 KY HK`[]自动选择`[]手动切换`[]DIRECT
custom_proxy_group=🗽 AI`select`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇸🇬 KY SG`[]🇺🇲 GF US`[]🇺🇲 SH US`[]🇺🇲 KY US`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇹🇼 KY TW`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇭🇰 KY HK`[]自动选择`[]手动切换`[]DIRECT
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🇨🇳 回国节点`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇭🇰 KY HK`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇹🇼 KY TW`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇸🇬 KY SG`[]🇺🇲 GF US`[]🇺🇲 SH US`[]🇺🇲 KY US`[]自动选择`[]手动切换
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=手动切换`select`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇹🇼 KY TW`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇸🇬 KY SG`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇭🇰 KY HK`[]🇺🇲 GF US`[]🇺🇲 SH US`[]🇺🇲 KY US`[]🇨🇳 回国节点`.*
custom_proxy_group=🇭🇰 GF HK`url-test`(Hongkong)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇹🇼 GF TW`url-test`(Taiwan)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇸🇬 GF SG`url-test`(Singapore)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇺🇲 GF US`url-test`(America)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇭🇰 SH HK`url-test`(香港0)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 SH TW`url-test`(台湾0)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 SH SG`url-test`(新加坡0|马来西亚0)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 SH US`url-test`(美国0)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇭🇰 KY HK`url-test`(【仅海外用户】香港)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇹🇼 KY TW`url-test`(【仅海外用户】台湾)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇸🇬 KY SG`url-test`(【仅海外用户】新加坡)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇺🇲 KY US`url-test`(【仅海外用户】美国)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇨🇳 回国节点`select`(日志记录)
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck