 [custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🎗️ Overseas,https://raw.githubusercontent.com/GIPtS/markray/main/tailormadeProxyTW.list
ruleset=📹 Emby_gf,https://raw.githubusercontent.com/GIPtS/markray/main/Emby_gf.list
ruleset=📹 Emby,https://raw.githubusercontent.com/GIPtS/markray/main/Emby_direct.list
ruleset=📹 Emby,https://raw.githubusercontent.com/GIPtS/markray/main/Emby.list
ruleset=🍎 Apple AI,https://raw.githubusercontent.com/GIPtS/markray/main/overseas.list
ruleset=🗽 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🗽 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Claude.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🎗️ Overseas`select`[]🇹🇼 DM TW`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇭🇰 DM HK`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇸🇬 DM SG`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇺🇲 DM US`[]🇺🇲 GF US`[]🇺🇲 SH US`[]自动选择`[]手动切换`[]DIRECT
custom_proxy_group=📹 Emby_gf`select`[]🇭🇰 DM HK`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇸🇬 DM SG`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇹🇼 DM TW`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇺🇲 DM US`[]🇺🇲 GF US`[]🇺🇲 SH US`[]自动选择`[]手动切换`[]DIRECT
custom_proxy_group=📹 Emby`select`[]DIRECT`[]🇭🇰 DM HK`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇸🇬 DM SG`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇹🇼 DM TW`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇺🇲 DM US`[]🇺🇲 GF US`[]🇺🇲 SH US`[]自动选择`[]手动切换
custom_proxy_group=🍎 Apple AI`select`[]🇸🇬 DM SG`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇹🇼 DM TW`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇭🇰 DM HK`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇺🇲 DM US`[]🇺🇲 GF US`[]🇺🇲 SH US`[]自动选择`[]手动切换`[]DIRECT
custom_proxy_group=🗽 AI`select`[]🇸🇬 DM SG`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇹🇼 DM TW`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇭🇰 DM HK`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇺🇲 DM US`[]🇺🇲 GF US`[]🇺🇲 SH US`[]自动选择`[]手动切换`[]DIRECT
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🇨🇳 回国节点`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇭🇰 DM HK`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇹🇼 DM TW`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇸🇬 DM SG`[]🇺🇲 GF US`[]🇺🇲 SH US`[]🇺🇲 DM US`[]自动选择`[]手动切换
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=手动切换`select`[]🇹🇼 DM TW`[]🇹🇼 GF TW`[]🇹🇼 SH TW`[]🇭🇰 DM HK`[]🇭🇰 GF HK`[]🇭🇰 SH HK`[]🇸🇬 DM SG`[]🇸🇬 GF SG`[]🇸🇬 SH SG`[]🇺🇲 DM US`[]🇺🇲 GF US`[]🇺🇲 SH US`[]🇨🇳 回国节点`.*
custom_proxy_group=🇭🇰 DM HK`url-test`^(?=.*香港)(?=.*(极速|TEST|专线|IPLC|落地)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 DM TW`url-test`^(?=.*台湾)(?=.*(极速|TEST|专线|IPLC|落地)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 DM SG`url-test`^(?=.*新加坡)(?=.*(极速|TEST|专线|IPLC|落地)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 DM US`url-test`^(?=.*美国)(?=.*(极速|TEST|专线|IPLC|落地)).*$`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇭🇰 GF HK`url-test`(Hongkong)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇹🇼 GF TW`url-test`(Taiwan)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇸🇬 GF SG`url-test`(Singapore)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇺🇲 GF US`url-test`(America)`http://www.gstatic.com/generate_204`300,,25
custom_proxy_group=🇭🇰 SH HK`url-test`^(?=.*香港)(?!.*(-|极速|TEST|专线|IPLC|IEPL)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 SH TW`url-test`^(?=.*台湾)(?!.*(-|极速|TEST|专线|IPLC|IEPL)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 SH SG`url-test`^(?=.*新加坡)(?!.*(-|极速|TEST|专线|IPLC|IEPL)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 SH US`url-test`^(?=.*美国)(?!.*(-|极速|TEST|专线|IPLC|IEPL)).*$`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 回国节点`select`(日志记录)
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck