[general]
dns_server = 223.5.5.5, 119.29.29.29, 8.8.8.8, 1.1.1.1

[Proxy Group]
# ==================== 1. 核心與動態優選策略組 ====================
# 利用 {{download}} 動態引入 Sub-Store 組合訂閱的所有節點
🚀 节点选择A = fallback, 🇭🇰 GF HK, 🇭🇰 DM HK, 🇹🇼 GF TW, 🇹🇼 DM TW, 🇸🇬 GF SG, 🇸🇬 DM SG, 🇺🇲 GF US, 🇺🇲 DM US, 🇺🇳 UN, ♻️ 自动选择, DIRECT
🚀 节点选择B = fallback, 🇭🇰 DM HK, 🇭🇰 GF HK, 🇹🇼 DM TW, 🇹🇼 GF TW, 🇸🇬 DM SG, 🇸🇬 GF SG, 🇺🇲 DM US, 🇺🇲 GF US, 🇺🇳 UN, ♻️ 自动选择, DIRECT

# 地區優選（使用正則表達式動態篩選組合訂閱節點）
🇭🇰 DM HK = url-test, {{download}}, policy-regex-filter=^(?=.*香港)(?=.*(极速|TEST|专线|IPLC|落地|V5)).*$, url=http://www.gstatic.com/generate_204, interval=300
🇭🇰 GF HK = url-test, {{download}}, policy-regex-filter=^(?=.*Hongkong)(?!.*境外入口).*$, url=http://www.gstatic.com/generate_204, interval=300
🇭🇰 香港节点 = select, 🇭🇰 DM HK, 🇭🇰 GF HK, DIRECT

🇹🇼 DM TW = url-test, {{download}}, policy-regex-filter=^(?=.*台湾)(?=.*(极速|TEST|专线|IPLC|落地|V5)).*$, url=http://www.gstatic.com/generate_204, interval=300
🇹🇼 GF TW = url-test, {{download}}, policy-regex-filter=^(?=.*Taiwan)(?!.*境外入口).*$, url=http://www.gstatic.com/generate_204, interval=300
🇹🇼 台湾节点 = select, 🇹🇼 DM TW, 🇹🇼 GF TW, DIRECT

🇸🇬 DM SG = url-test, {{download}}, policy-regex-filter=^(?=.*新加坡)(?=.*(极速|TEST|专线|IPLC|落地|V5)).*$, url=http://www.gstatic.com/generate_204, interval=300
🇸🇬 GF SG = url-test, {{download}}, policy-regex-filter=^(?=.*Singapore)(?!.*境外入口).*$, url=http://www.gstatic.com/generate_204, interval=300
🇸🇬 狮城节点 = select, 🇸🇬 DM SG, 🇸🇬 GF SG, DIRECT

🇺🇲 DM US = url-test, {{download}}, policy-regex-filter=^(?=.*美国)(?=.*(极速|TEST|专线|IPLC|落地|V5)).*$, url=http://www.gstatic.com/generate_204, interval=300
🇺🇲 GF US = url-test, {{download}}, policy-regex-filter=^(?=.*America)(?!.*境外入口).*$, url=http://www.gstatic.com/generate_204, interval=300
🇺🇲 美国节点 = select, 🇺🇲 DM US, 🇺🇲 GF US, DIRECT

🇺🇳 UN = url-test, {{download}}, policy-regex-filter=^(?!.*(美国|US|United States|America|香港|HK|Hong Kong|Hongkong|台|新北|彰化|TW|Taiwan|新加坡|SG|Singapore|马来西亚|MY|Malaysia)).*$, url=http://www.gstatic.com/generate_204, interval=300
♻️ 自动选择 = url-test, {{download}}, policy-regex-filter=^(?!.*(美国|US|United States|America|香港|HK|Hong Kong|Hongkong|台|新北|彰化|TW|Taiwan|新加坡|SG|Singapore|马来西亚|MY|Malaysia)).*$, url=http://www.gstatic.com/generate_204, interval=300

# ==================== 2. 業務分流策略組 ====================
📹 Emby_proxy_a = select, 🚀 节点选择A, 🚀 节点选择B, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连
📹 Emby_proxy_b = select, 🚀 节点选择B, 🚀 节点选择A, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连
📹 Emby_direct = select, 🎯 全球直连, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🚀 节点选择A, 🚀 节点选择B
Ⓜ️ WFH = select, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B, 🇭🇰 香港节点
📢 谷歌FCM = select, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
💬 Ai平台 = select, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
📹 Youtube = select, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
📲 Telegram = select, 🇸🇬 狮城节点, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
📲 Line = select, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
🎧 Spotify = select, 🇹🇼 台湾节点, 🇭🇰 香港节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
🌍 国外媒体 = select, 🇹🇼 台湾节点, 🇭🇰 香港节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
🎗 国外网站 = select, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
Ⓜ️ 微软Bing = select, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
Ⓜ️ 微软服务 = select, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
🎥 Netflix = select, 🇹🇼 台湾节点, 🇭🇰 香港节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B
📺 哔哩哔哩 = select, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点
🌏 国内媒体 = select, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点
🍎 苹果服务 = select, 🎯 全球直连, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🚀 节点选择A, 🚀 节点选择B
🎮 游戏平台 = select, 🎯 全球直连, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🚀 节点选择A, 🚀 节点选择B
✈️ Speedtest = select, DIRECT, 🇭🇰 GF HK, 🇭🇰 DM HK, 🇹🇼 GF TW, 🇹🇼 DM TW, 🇸🇬 GF SG, 🇸🇬 DM SG, 🇺🇲 GF US, 🇺🇲 DM US, 🇺🇳 UN, ♻️ 自动选择
🎯 全球直连 = select, DIRECT, 🇭🇰 GF HK, 🇭🇰 DM HK, 🇹🇼 GF TW, 🇹🇼 DM TW, 🇸🇬 GF SG, 🇸🇬 DM SG, 🇺🇲 GF US, 🇺🇲 DM US, 🇺🇳 UN, ♻️ 自动选择
🛑 广告拦截 = select, REJECT, DIRECT
🍃 应用净化 = select, REJECT, DIRECT
🐟 漏网之鱼 = select, 🇭🇰 香港节点, 🇹🇼 台湾节点, 🇺🇲 美国节点, 🇸🇬 狮城节点, 🎯 全球直连, 🚀 节点选择A, 🚀 节点选择B

[Rule]
# ==================== 3. 遠程分流規則引用 ====================
RULE-SET,https://raw.githubusercontent.com/GIPtS/markray/main/WFH.list,Ⓜ️ WFH
RULE-SET,https://raw.githubusercontent.com/GIPtS/markray/main/TailormadeDirect.list,🎯 全球直连
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,🎯 全球直连
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list,🎯 全球直连
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.list,🎯 全球直连
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list,✈️ Speedtest
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,🛑 广告拦截
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,🍃 应用净化
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list,📢 谷歌FCM
RULE-SET,https://raw.githubusercontent.com/GIPtS/markray/main/overseas.list,💬 Ai平台
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,🎯 全球直连
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,🎯 全球直连
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list,🍎 苹果服务
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list,Ⓜ️ 微软Bing
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list,Ⓜ️ 微软服务
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list,Ⓜ️ 微软服务
RULE-SET,https://raw.githubusercontent.com/GIPtS/markray/main/Emby_direct.list,📹 Emby_direct
RULE-SET,https://raw.githubusercontent.com/GIPtS/markray/main/Emby_gf.list,🇭🇰 GF HK
RULE-SET,https://raw.githubusercontent.com/GIPtS/markray/main/Emby_proxy.list,📹 Emby_proxy_a
RULE-SET,https://raw.githubusercontent.com/GIPtS/markray/main/Emby_BC.list,📹 Emby_proxy_b
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list,📹 Youtube
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list,📲 Telegram
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Line.list,📲 Line
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list,📢 谷歌FCM
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list,📢 谷歌FCM
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Claude.list,💬 Ai平台
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list,💬 Ai平台
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list,🎮 游戏平台
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list,🎮 游戏平台
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list,🎮 游戏平台
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list,🎮 游戏平台
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list,🎮 游戏平台
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list,🎥 Netflix
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list,🎧 Spotify
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list,📺 哔哩哔哩
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list,📺 哔哩哔哩
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list,🌏 国内媒体
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list,🌍 国外媒体
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list,🎗 国外网站
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,🎯 全球直连
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,🎯 全球直连
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list,🎯 全球直连

GEOIP,CN,🎯 全球直连
FINAL,🐟 漏网之鱼
